@startuml
title Deployment Shop
left to right direction
cloud "Presentation Layer" as pl {
  frame "Client" as pl_client {
    node "Browser" as web {
      [Website-Frontend]
    }
    node "Mobile Devices" as app {
      [IOS]
      [Android]
    }
  }
}

node "Load Balancer" as lb_front {
  [Proxy Balancer] as lb_front1
}

node "Application Layer" as al {
  frame "Application Server 1" as as1 {
    [Application Server 1a] as as_1a
    [Application Server 1b] as as_1b
  }
  frame "Application Server 2" as as2 {
    [Application Server 2a] as as_2a
    [Application Server 2b] as as_2b
  }
  frame "Application Server  ..." as "as..." {
    [Application Server ...] as as_...
  }
}

node "Load Balancer" as lb_back {
  [Proxy Balancer] as lb_back1
}

node "Persistence Layer" as dbl {
  frame "Database Server 1" {
    database "Account Schema" as db_1a
    database "Product Schema" as db_1b
    database "Invoice/Order Schema" as db_1c

  }
  frame "Database Server 2" {
    [Database Server 2a] as db_2a
    [Database Server 2b] as db_2b
  }
  frame "Database Server ..." {
    [Database Server ...] as db_...
  }
}

/'assoziationen'/
pl_client -- lb_front1 :http

lb_front1 -- as_1a
lb_front1 -- as_1b
lb_front1 -- as_2a
lb_front1 -- as_2b
lb_front1 -- as_...

as_1a -- lb_back1
as_1b -- lb_back1
as_2a -- lb_back1
as_2b -- lb_back1
as_... -- lb_back1

lb_back1 -- db_1a
lb_back1 -- db_1b
lb_back1 -- db_2a
lb_back1 -- db_2b
lb_back1 -- db_...


/'skinparam componentStyle uml2
package "Some Group" {
  interface HTTP as httpEndpoint
  [First Component]
  [Another Component]
}
node "Other Groups" {
  FTP - [Second Component]
}
cloud {
  [Example 1]
}
database "MySql" {
  folder "This is my folder" {
    [Folder 3]
  }
  frame "Foo" {
    [Frame 4]
  }
}
httpEndpoint - [First Component]
[First Component] --> FTP
[Another Component] --> [Example 1]
[Example 1] --> [Folder 3]'/
@enduml
